name: MyCustomCI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: nodeTest
        run: node test.js ${{ secrets.MY_SECRET }}

      - name: pwdTest
        run: cd ../;pwd

      - name: pwdTest2
        run: cd ../;pwd
