name: MyCustomCI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: nodeTest
        run: node test.js $MY_SECRET
