name: MyCustomCI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: nodeTest
        run: node test.js ${{ secrets.MY_SECRET }}

      - name: pwdTest
        run: cd ../;pwd

      # 테스트해본 바, 두 테스트의 결과가 같았다. 그러므로 한 스텝 단위로 실행된다.
      - name: pwdTest2
        run: cd ../;pwd

      - name: multilineTest
        run: |
          cd ../;
          mkdir myDir;
          cd myDir;
          echo "This is test file" > test.txt;
          pwd;
          cat test.txt
