name: MyCustomCI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: printText
        run: echo "Hello CI!"

      - name: osTest
        run: pwd

      - name: ll
        run: ls -al

      - name: cat
        run: cat README.md

      - name: dumb
        run: echo $MY_SECRET > test.txt

      - name: show
        run: cat test.txt
